module:
  target: models.lpieps.LPIEPS
  params:
    lr: 1e-4
    log_interval: 100
    use_mlp: False
    loss_config:
      target: losses.multi_level_triplet.MultiLevelTripletLoss
      params:
        margin_fine: 0.05
        margin_coarse: 0.05
        lambda_identity: 2.0

data:
  target: datasets.util.DataModuleFromConfig
  params:
    num_workers: 4
    batch_size: 4
    wrap: True
    train:
      target: datasets.anime_triplet.AnimeTripletDataset
      params:
        root: '/local_datasets/anime'
        # root: 'D:/datasets/anime'
        train: True
        size: [384, 384]
        scale: [ 0.75, 1.0 ]

    validation:
      target: datasets.anime_triplet.AnimeTripletDataset
      params:
        root: '/local_datasets/anime'
        # root: 'D:/datasets/anime'
        train: False
        size: [384, 384]
        scale: [ 0.75, 1.0 ]

logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'lpieps'
    version: 'conv'


checkpoints:
  latest_checkpoints:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/lpieps/conv'
      filename: 'last'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1

  best_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/lpieps/conv'
      filename: 'best'
      monitor: 'valid/total_loss'
      mode: 'min'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 600
  # accumulate_grad_batches: 2
  # precision: 'bf16'